---
active_modules:
    - blog
    - tags
    - pygments
    - latex

author: "稻草人.L"
canonical_url: /develop-notes/
#canonical_url: http://scarecrow-notes.appspot.com

modules:
    pygments:
        style: tango
